### ISSUE TITLE
Haupt-Domain umschalten?

### ISSUE THREAD

**Issue by ccoenen** [IF2023/IF2023#11]
Soll ich die Haupt-Domain schon auf die 2023-er Seite umleiten? Die Vorschau-Seite ist ja an sich OK?

**Comment by Nilsosi** [comment]
Sehr gerne. Da wollte ich sie eh die Tage ansprechen. Danke sehr.

**Comment by ccoenen** [comment]
ich habe im Moment eine Weiterleitung auf 2023 drin, und später sollte (automatisch) auch die Domain selbst auf diesen Ordner zeigen.

**Comment by ccoenen** [comment]
yup, scheint jetzt auch auf der Domain selbst normal aktiv zu sein ohne Weiterleitung.
